services:
  api:
    image: ghcr.io/likp/pxwebapi:v0.0.1
    ports:
      - "8080:8080"
    networks:
      px-network:
        ipv4_address: 192.168.70.66
    volumes:
      - px-database:/app/wwwroot/Database
    environment:
      - ADMINPROTECTION__IPWHITELIST__0=192.168.70.10
    healthcheck:
      test:  curl -f http://localhost:8080/api/v2/config || exit 1
      interval: 10s
      timeout: 5s
      retries: 5   
  init-api:
    image: curlimages/curl:8.10.1
    command: /bin/sh -c "echo \"$$INIT_SCRIPT\" > /tmp/init-px.sh; chmod +x /tmp/init-px.sh; sh /tmp/init-px.sh"
    environment:
      INIT_SCRIPT: |-
        #!/bin/sh

        if [ -f /app/wwwroot/Database/.init_done ]; then
            echo "Init already done"
            exit 0
        fi

        curl -I -X PUT -H "API_ADMIN_KEY: test" http://api:8080/api/v2/admin/database

        FIL="/app/wwwroot/Database/Menu.xml"

        echo $$FIL
        #Get the file hash
        LAST_MODIFIED=$$(stat -c %Y "$$FIL")

        # Poll the file for changes
        while true; do
            # Hämta den aktuella tidpunkten då filen senast ändrades
            CURRENT_MODIFIED=$$(stat -c %Y "$$FIL")
            
            # Kolla om filen har ändrats
            if [ "$$CURRENT_MODIFIED" -ne "$$LAST_MODIFIED" ]; then
                echo "Filen har ändrats!"
                # Small wait to make sure the file is done being written to disk
                sleep 2
                # Initialize the search index creation
                curl -I -X POST -H "API_ADMIN_KEY: test" http://api:8080/api/v2/admin/searchindex
                touch /app/wwwroot/Database/.init_done
                exit 0
            fi

            # Vänta 1 sekund innan nästa koll
            sleep 1
        done
        
    depends_on:
      api:
        condition: service_healthy
    networks:
      px-network:
        ipv4_address: 192.168.70.10
    volumes:
      - px-database:/app/wwwroot/Database


  pxweb2-init:
    image: ghcr.io/likp/pxweb2:v0.0.1
    command: /bin/sh -c "echo \"$$INIT_SCRIPT\" > /tmp/init-pxweb.sh; chmod +x /tmp/init-pxweb.sh; sh /tmp/init-pxweb.sh"
    environment:
      INIT_SCRIPT: |-
        #!/bin/sh

        cp /usr/share/nginx/html/config/config.js /cfg/config.js
        sed -i 's|https://api.scb.se/OV0104/v2beta/api/v2|http://localhost:8080/api/v2|g' /cfg/config.js

        tableId=$(grep -m 1 "<Link" /db/Menu.xml | sed -n 's/.*tableId="\([^"]*\)".*/\1/p')
        echo "http://localhost:8888/table/$$tableId"
       
    networks:
      px-network:
        ipv4_address: 192.168.70.22
    volumes:
      - px-web-config:/cfg
      - px-database:/db
    depends_on:
      init-api:
        condition: service_completed_successfully
  pxweb:
    image: ghcr.io/likp/pxweb2:v0.0.1
    ports:
      - "8888:8080"   
    networks:
      px-network:
        ipv4_address: 192.168.70.24
    volumes:
      - px-web-config:/usr/share/nginx/html/config
    depends_on:
      pxweb2-init:
        condition: service_completed_successfully
networks:
  px-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 192.168.70.0/24
        gateway: 192.168.70.1

volumes: 
  px-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PX_DATABASE_PATH:?error}
  px-web-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PX_WEB_CONFIG_PATH:?error}